app:
  name: streamlink
  rel: 1
  entry: streamlink
git:
  repo: https://github.com/streamlink/streamlink.git
  ref: f7be2514407ccda542f0d113066827d48414f09b
builds:
  aarch64:
    image: ghcr.io/streamlink/appimage-buildenv-aarch64@sha256:207dc908f020450588f77b54ee05904ee716f9f7cc71c02a9ea7276e77d37078
    tag: manylinux_2_28_aarch64
    abi: cp314-cp314
    bundles:
      ffmpeg:
        filename: ffmpeg-n8.1-5-g3ec48e4bc6-linuxarm64-gpl-8.1.tar.xz
        url: https://github.com/streamlink/FFmpeg-Builds/releases/download/20260323-1/ffmpeg-n8.1-5-g3ec48e4bc6-linuxarm64-gpl-8.1.tar.xz
        sha256: b9f3f76cb80d2095881e8ea9d34556dbd2d59aad2e02d44ab2287d6c828c2cd4
        type: tar
        sourcedir: ffmpeg-n8.1-5-g3ec48e4bc6-linuxarm64-gpl-8.1
        files:
          - from: bin/ffmpeg
            to: usr/bin/ffmpeg
          - from: LICENSE.txt
            to: usr/share/licenses/ffmpeg.txt
          - from: BUILDINFO.txt
            to: usr/share/ffmpeg/buildinfo.txt
  x86_64:
    image: ghcr.io/streamlink/appimage-buildenv-x86_64@sha256:880cfbf9190c1d1c302d6c86f45fbf98c5c788489d8c65abebda9dbf62d4abb1
    tag: manylinux_2_28_x86_64
    abi: cp314-cp314
    bundles:
      ffmpeg:
        filename: ffmpeg-n8.1-5-g3ec48e4bc6-linux64-gpl-8.1.tar.xz
        url: https://github.com/streamlink/FFmpeg-Builds/releases/download/20260323-1/ffmpeg-n8.1-5-g3ec48e4bc6-linux64-gpl-8.1.tar.xz
        sha256: e163d754a10a358788a3640d426039daf8ea281572233b8b58d60255a4106cc8
        type: tar
        sourcedir: ffmpeg-n8.1-5-g3ec48e4bc6-linux64-gpl-8.1
        files:
          - from: bin/ffmpeg
            to: usr/bin/ffmpeg
          - from: LICENSE.txt
            to: usr/share/licenses/ffmpeg.txt
          - from: BUILDINFO.txt
            to: usr/share/ffmpeg/buildinfo.txt
